workspace: FCA
connections:
  azure_connection : fca azure management

folders:
  - name: "Deployment"
    items:
    - FCA.Lakehouse
    - Init_FCA_Lakehouse_Tables.Notebook
    - Update_FCA_delivery.Notebook
  - name: "Focus"
    items:
    - 01_Load_Calendar.Notebook
    - 01_Load_Dimensions.Notebook
    - 01_Load_Focus_Fabric.Notebook
    - 01_Load_FCAVersion.Notebook
    - 01_Load_Focus.Notebook
    - 01_Load_Meters.Notebook
    - Load FCA E2E.DataPipeline
  - name: "Data Agent"
    items:
    - 02_Create_DataAgent.Notebook
  - name: "Reservations"
    items:
    - 02_Load_DimReservation.Notebook
    - 02_Load_Reservation_Fabric.Notebook
    - 02_Load_Reservation.Notebook
    - Load Reservations.DataPipeline
  - name: "Quotas"
    items:
    - 02_Load_Quota_Fabric.Notebook
    - Load Quota.DataPipeline
  - name: "Maintenance"
    items:
    - 03_Optimization.Notebook
  - name: "Reporting"
    items:
    - FCA_Core_Report.Report
    - FCA_Core_SM.SemanticModel

