table 'Calc Dependencies'
	lineageTag: d4fd23fd-b825-42ec-b528-109c6a85d395

	column DATABASE_NAME
		dataType: string
		lineageTag: 5ac9363f-421d-4158-b0b8-016b9a1376c5
		summarizeBy: none
		sourceColumn: DATABASE_NAME

		annotation SummarizationSetBy = Automatic

	column OBJECT_TYPE
		dataType: string
		lineageTag: 5f1b458b-97b3-4664-838a-96d7809fdc4c
		summarizeBy: none
		sourceColumn: OBJECT_TYPE

		annotation SummarizationSetBy = Automatic

	column TABLE
		dataType: string
		lineageTag: f9aa2321-c4d5-400e-b13a-2444236b9a8f
		summarizeBy: none
		sourceColumn: TABLE

		annotation SummarizationSetBy = Automatic

	column OBJECT
		dataType: string
		lineageTag: 32700378-381f-4e79-9810-42bd6c4db46d
		summarizeBy: none
		sourceColumn: OBJECT

		annotation SummarizationSetBy = Automatic

	column EXPRESSION
		dataType: string
		lineageTag: cf0d781f-4a52-4d1b-ba78-81ea7a4811b1
		summarizeBy: none
		sourceColumn: EXPRESSION

		annotation SummarizationSetBy = Automatic

	column REFERENCED_OBJECT_TYPE
		dataType: string
		lineageTag: b6a3ddc6-22d3-4105-903e-c60daefd97e5
		summarizeBy: none
		sourceColumn: REFERENCED_OBJECT_TYPE

		annotation SummarizationSetBy = Automatic

	column REFERENCED_TABLE
		dataType: string
		lineageTag: a5113504-335b-4bdc-80d6-13a0b6992cba
		summarizeBy: none
		sourceColumn: REFERENCED_TABLE

		annotation SummarizationSetBy = Automatic

	column REFERENCED_OBJECT
		dataType: string
		lineageTag: 26b8b1d6-f100-4d93-8d0c-89b0fbd87164
		summarizeBy: none
		sourceColumn: REFERENCED_OBJECT

		annotation SummarizationSetBy = Automatic

	column REFERENCED_EXPRESSION
		dataType: string
		lineageTag: b9a8e426-e4d3-4308-a30b-df3121b02f47
		summarizeBy: none
		sourceColumn: REFERENCED_EXPRESSION

		annotation SummarizationSetBy = Automatic

	column QUERY
		dataType: string
		lineageTag: 6ceec01e-bd2b-44a9-bda2-264ede2a62a2
		summarizeBy: none
		sourceColumn: QUERY

		annotation SummarizationSetBy = Automatic

	column TableObjectKey = 'Calc Dependencies'[TABLE] & "-" & 'Calc Dependencies'[OBJECT]
		lineageTag: cb5d4d18-f3b7-430f-9324-16e7fa0fb8b3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Table SystemFlags'
		dataType: int64
		formatString: 0
		lineageTag: 041c8baa-89b4-42da-abab-ed9d3e2e92ba
		summarizeBy: sum
		sourceColumn: Table SystemFlags

		annotation SummarizationSetBy = Automatic

	column 'Referenced Table SystemFlags'
		dataType: int64
		formatString: 0
		lineageTag: e28c3b0d-0080-4043-96b8-981fff3ec0a8
		summarizeBy: sum
		sourceColumn: Referenced Table SystemFlags

		annotation SummarizationSetBy = Automatic

	column 'Is Internal Table' = IF('Calc Dependencies'[Table SystemFlags]=0,"No", "Yes")
		lineageTag: 750439eb-8e2d-42d3-bf09-333eef5f74bd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Internal Referenced Table' = IF('Calc Dependencies'[Referenced Table SystemFlags]=0,"No", "Yes")
		lineageTag: 1982d1b7-134a-4934-b861-a3e8294f503f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SingularName
		dataType: string
		lineageTag: 6ba3997e-3c94-4961-82f4-a993c1f01b86
		summarizeBy: none
		sourceColumn: SingularName

		annotation SummarizationSetBy = Automatic

	column PluralName
		dataType: string
		lineageTag: a62927f8-3cf4-4cf1-b75d-dd602834f169
		summarizeBy: none
		sourceColumn: PluralName

		annotation SummarizationSetBy = Automatic

	column SingularNameReferenced
		dataType: string
		lineageTag: e4cc202c-fe22-49e7-bfcd-209d3b8b0898
		summarizeBy: none
		sourceColumn: SingularNameReferenced

		annotation SummarizationSetBy = Automatic

	column PluralNameReferenced
		dataType: string
		lineageTag: 9aa003a1-81c4-4346-bf21-d5e845e4c765
		summarizeBy: none
		sourceColumn: PluralNameReferenced

		annotation SummarizationSetBy = Automatic

	partition 'Calc Dependencies' = m
		mode: import
		queryGroup: Discover
		source =
				let
				    Source = AnalysisServices.Database(serverURL, modelName, [Query="SELECT * FROM $System.DISCOVER_CALC_DEPENDENCY", Implementation="2.0"]),
				    #"Merged Queries" = Table.NestedJoin(Source, {"TABLE"}, #"Tables TM", {"Table Name"}, "Tables TM", JoinKind.LeftOuter),
				    #"Expanded Tables TM" = Table.ExpandTableColumn(#"Merged Queries", "Tables TM", {"SystemFlags"}, {"SystemFlags"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Tables TM", {"REFERENCED_TABLE"}, #"Tables TM", {"Table Name"}, "Tables TM", JoinKind.LeftOuter),
				    #"Expanded Tables TM1" = Table.ExpandTableColumn(#"Merged Queries1", "Tables TM", {"SystemFlags"}, {"SystemFlags.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Tables TM1",{{"SystemFlags", "Table SystemFlags"}, {"SystemFlags.1", "Referenced Table SystemFlags"}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Renamed Columns", {"OBJECT_TYPE"}, #"Object Type Names", {"OriginalValue"}, "Object Type Names", JoinKind.LeftOuter),
				    #"Expanded Object Type Names" = Table.ExpandTableColumn(#"Merged Queries2", "Object Type Names", {"SingularName", "PluralName"}, {"SingularName", "PluralName"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Expanded Object Type Names", {"REFERENCED_OBJECT_TYPE"}, #"Object Type Names", {"OriginalValue"}, "Object Type Names", JoinKind.LeftOuter),
				    #"Expanded Object Type Names1" = Table.ExpandTableColumn(#"Merged Queries3", "Object Type Names", {"SingularName", "PluralName"}, {"SingularName.1", "PluralName.1"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Object Type Names1",{{"SingularName.1", "SingularNameReferenced"}, {"PluralName.1", "PluralNameReferenced"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

