table 'Column Alignment ENUM'
	isHidden
	lineageTag: cc1b2308-0ef6-45ca-9581-584ebd4fa4c4

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: e1c0a4d9-b5f6-47df-b3c6-325e25138699
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column Alignment
		dataType: string
		lineageTag: a48b5430-7b6a-49b6-9d21-7f61fb43cb15
		summarizeBy: none
		sourceColumn: Alignment

		annotation SummarizationSetBy = Automatic

	partition 'Column Alignment ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXJJTUsszSlRitWJVjIC8n1S0yAcYyAnKDM9A8IzAfKcU/NKUouUYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "Alignment"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

