table 'Columns TM'
	lineageTag: f9b18b8a-d882-4d4d-8419-3c14d21bfee6

	column ID
		dataType: double
		lineageTag: ae45e164-df12-4735-805e-29cd5c9c31db
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TableID
		dataType: double
		lineageTag: 2c746fa8-5e3d-4cfe-8ab3-a41d033f7ef8
		summarizeBy: none
		sourceColumn: TableID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Column Name'
		dataType: string
		lineageTag: 8d5d9996-396e-4faf-ba69-205f75453238
		summarizeBy: none
		sourceColumn: Column Name

		annotation SummarizationSetBy = Automatic

	column InferredName
		dataType: string
		lineageTag: 806c1446-e87c-4d73-b599-03c82f1d6260
		summarizeBy: none
		sourceColumn: InferredName

		annotation SummarizationSetBy = Automatic

	column ExplicitDataType
		dataType: int64
		formatString: 0
		lineageTag: 190302c0-eb9d-48c7-b3c0-32a2f06133cc
		summarizeBy: none
		sourceColumn: ExplicitDataType

		annotation SummarizationSetBy = Automatic

	column InferredDataType
		dataType: int64
		formatString: 0
		lineageTag: c81b0a0d-e42a-440e-8cd4-d207673f4c32
		summarizeBy: sum
		sourceColumn: InferredDataType

		annotation SummarizationSetBy = Automatic

	column DataCategory
		dataType: string
		lineageTag: 5c4a16bc-3735-4e52-a67b-80746b1a0519
		summarizeBy: none
		sourceColumn: DataCategory

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 0192806f-f324-4011-a2b7-866c73b85ba8
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3c02304c-6f21-472c-94af-13c55ef453b9
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: int64
		formatString: 0
		lineageTag: c5b7dcaa-09c0-4750-8a9e-1d3c9756db16
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column IsUnique
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca739fe1-c34b-4e6b-8abe-cca0a06549e3
		summarizeBy: none
		sourceColumn: IsUnique

		annotation SummarizationSetBy = Automatic

	column IsKey
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b37b9009-706a-45c0-856c-30690bce3886
		summarizeBy: none
		sourceColumn: IsKey

		annotation SummarizationSetBy = Automatic

	column IsNullable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5467a90a-e173-4ec3-b0c6-73acd1732b12
		summarizeBy: none
		sourceColumn: IsNullable

		annotation SummarizationSetBy = Automatic

	column Alignment
		dataType: int64
		formatString: 0
		lineageTag: 98bf2c33-e716-43c0-a6e7-d48430385fe9
		summarizeBy: none
		sourceColumn: Alignment

		annotation SummarizationSetBy = Automatic

	column TableDetailPosition
		dataType: int64
		formatString: 0
		lineageTag: 94ddf351-dff2-4bf4-b503-1168e7938675
		summarizeBy: sum
		sourceColumn: TableDetailPosition

		annotation SummarizationSetBy = Automatic

	column IsDefaultLabel
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f8d77652-16ab-4d62-ba6c-aea213ace9d5
		summarizeBy: none
		sourceColumn: IsDefaultLabel

		annotation SummarizationSetBy = Automatic

	column IsDefaultImage
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9eb422d4-acbe-409d-8e1e-4655d0d47813
		summarizeBy: none
		sourceColumn: IsDefaultImage

		annotation SummarizationSetBy = Automatic

	column SummarizeBy
		dataType: int64
		formatString: 0
		lineageTag: e86e1a79-3adc-4644-8a76-dbd91cac0853
		summarizeBy: none
		sourceColumn: SummarizeBy

		annotation SummarizationSetBy = Automatic

	column ColumnStorageID
		dataType: double
		lineageTag: 52e3791c-6736-46b5-afe8-b125e6053e86
		summarizeBy: count
		sourceColumn: ColumnStorageID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type
		dataType: int64
		formatString: 0
		lineageTag: 9d3e466c-60d2-4ff4-8dc9-0949ee670903
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column SourceColumn
		dataType: string
		lineageTag: d1bc1b8c-a8d5-4dda-b439-4a03bc2e8f2d
		summarizeBy: none
		sourceColumn: SourceColumn

		annotation SummarizationSetBy = Automatic

	column ColumnOriginID
		dataType: double
		lineageTag: 4a0e1287-34c2-4522-9d6a-589c3aef652c
		summarizeBy: count
		sourceColumn: ColumnOriginID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Expression
		dataType: string
		lineageTag: 1232c3ca-afaa-4fae-8865-7445b4da8dd7
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column FormatString
		dataType: string
		lineageTag: 2d43fb99-26ca-40d0-9de0-a35c256481bb
		summarizeBy: none
		sourceColumn: FormatString

		annotation SummarizationSetBy = Automatic

	column IsAvailableInMDX
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 38b1afa2-e22c-4348-8495-8ea28da7d4a0
		summarizeBy: none
		sourceColumn: IsAvailableInMDX

		annotation SummarizationSetBy = Automatic

	column SortByColumnID
		dataType: double
		lineageTag: caa119c2-8670-4343-aed9-83f9d704eca0
		summarizeBy: count
		sourceColumn: SortByColumnID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AttributeHierarchyID
		dataType: double
		lineageTag: 7ed3a01f-d621-4865-8b4b-a33ec10c3e46
		summarizeBy: count
		sourceColumn: AttributeHierarchyID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 58d062e3-feb1-46ce-b0f3-79997a6e328d
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column StructureModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: cc3f2417-075f-4c8c-b4f8-40f7dfc718c4
		summarizeBy: none
		sourceColumn: StructureModifiedTime

		annotation SummarizationSetBy = Automatic

	column RefreshedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 95933be2-df41-4985-a9e5-9477fa9fb6f0
		summarizeBy: none
		sourceColumn: RefreshedTime

		annotation SummarizationSetBy = Automatic

	column SystemFlags
		dataType: int64
		formatString: 0
		lineageTag: f15eba54-3cb6-405f-a54d-75517459b6ac
		summarizeBy: sum
		sourceColumn: SystemFlags

		annotation SummarizationSetBy = Automatic

	column KeepUniqueRows
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 407eb297-0658-4a3c-b9ac-15ae23f8dc84
		summarizeBy: none
		sourceColumn: KeepUniqueRows

		annotation SummarizationSetBy = Automatic

	column DisplayOrdinal
		dataType: int64
		formatString: 0
		lineageTag: 87cf7fed-f4cc-424f-ae68-7072ea02a36b
		summarizeBy: sum
		sourceColumn: DisplayOrdinal

		annotation SummarizationSetBy = Automatic

	column ErrorMessage
		dataType: string
		lineageTag: 45b0ab7a-dd63-44ce-bbd6-dcd5f8e3ccf0
		summarizeBy: none
		sourceColumn: ErrorMessage

		annotation SummarizationSetBy = Automatic

	column SourceProviderType
		dataType: string
		lineageTag: 6f5879fa-6369-417f-8413-b8bbbb2cecc2
		summarizeBy: none
		sourceColumn: SourceProviderType

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		dataType: string
		lineageTag: 22f2099f-6271-42b0-ba9b-f6cdc06eabab
		summarizeBy: none
		sourceColumn: DisplayFolder

		annotation SummarizationSetBy = Automatic

	column EncodingHint
		dataType: int64
		formatString: 0
		lineageTag: 43d9dca7-3755-4042-84cb-b6851481b4ca
		summarizeBy: none
		sourceColumn: EncodingHint

		annotation SummarizationSetBy = Automatic

	column 'IsKey Icon' = IF('Columns TM'[IsKey]=TRUE(),"🔑","🗄️")
		dataType: string
		lineageTag: 3a4e7ac2-6ab2-468a-b112-abb067d12035
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Is Hidden Icon' = IF('Columns TM'[IsHidden]=TRUE(),"❌", "👁️‍🗨️")
		lineageTag: c8f7f422-e55e-4d01-9268-b16881aed666
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AlternateOfID
		dataType: double
		lineageTag: 16250524-2e23-449e-b23f-eb4fcd7ee0e3
		summarizeBy: count
		sourceColumn: AlternateOfID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineageTag
		dataType: string
		lineageTag: 79bd3a54-bfe5-4fa2-b250-8382af713397
		summarizeBy: none
		sourceColumn: LineageTag

		annotation SummarizationSetBy = Automatic

	column SourceLineageTag
		dataType: string
		lineageTag: 678e39a8-dfef-4ab9-83e7-55a6304d3570
		summarizeBy: none
		sourceColumn: SourceLineageTag

		annotation SummarizationSetBy = Automatic

	column ExplicitName
		dataType: string
		lineageTag: 47070586-cb9b-4bd8-b8d9-1e4de26941b5
		summarizeBy: none
		sourceColumn: ExplicitName

		annotation SummarizationSetBy = Automatic

	column Encoding = LOOKUPVALUE('Storage Table Columns TM'[Encoding], 'Storage Table Columns TM'[ExtractedColumnID], 'Columns TM'[ID], 'Storage Table Columns TM'[COLUMN_TYPE], "BASIC_DATA")
		lineageTag: 3bca2eb4-61e4-478c-8ba1-e8fb7ee3b2b9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column RelatedColumnDetailsID
		dataType: double
		lineageTag: d4d24977-a205-44df-8fd3-1a21904aadbf
		summarizeBy: count
		sourceColumn: RelatedColumnDetailsID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Encoding Hint' = RELATED('Column EncodingHint ENUM'[Encoding Hint])
		lineageTag: 631a6ad9-a2a6-42e6-b494-090e0c0adcdf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accepted Encoding Hints' = ```
			
			IF(
			    'Columns TM'[Encoding Hint] <> "Default" && 'Columns TM'[Encoding] = 'Columns TM'[Encoding Hint],
			    "Accepted", 
			    IF(
			        'Columns TM'[Encoding Hint] = "Default",
			        BLANK(),
			        "Not Accepted"
			    )
			)
			```
		lineageTag: 84fd4af4-1a9b-4d2e-a2ed-8966be0ae5da
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Columns TM' = m
		mode: import
		queryGroup: 'Meta Data'
		source =
				let
				    #"Columns TM" = AnalysisServices.Database(serverURL, modelName, [Query="SELECT * FROM $System.TMSCHEMA_COLUMNS", Implementation="2.0"]),
				    #"Added Conditional Column" = Table.AddColumn(#"Columns TM", "Column Name", each if [ExplicitName] = null then [InferredName] else [ExplicitName]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Column Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

