table 'Column SummarizeBy ENUM'
	isHidden
	lineageTag: b0d133c7-e563-46c6-b46b-33281a234f4d

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: 8a5ca891-198d-474e-bb82-d16729a6fa34
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column SummarizeBy
		dataType: string
		lineageTag: 3de574d6-c182-4f1e-ad40-44a47a0c41b3
		summarizeBy: none
		sourceColumn: SummarizeBy

		annotation SummarizationSetBy = Automatic

	partition 'Column SummarizeBy ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXJJTUsszSlRitWJVjIC8v3y81LBHGMgJ7g0F8w2AbJ9M/PAbFMQO7ECzDYDsp3zS/Mg2s2BPMey1KLEdIgJFiDjM4tLMvOSS6CqYgE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "SummarizeBy"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

