table 'CrossFilteringBehavior ENUM'
	lineageTag: ae7f99f9-0a14-4cfc-a0a5-9f06896297b7

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: 45e41f53-dcc0-49b5-9a9a-d355ce32d9f4
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column 'CrossFilteringBehavior Name'
		dataType: string
		lineageTag: 980d49e0-42de-46e9-8dda-184249ae008a
		summarizeBy: none
		sourceColumn: CrossFilteringBehavior Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 193ffe6a-59df-48e9-b949-6b23de578bc5
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition 'CrossFilteringBehavior ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zZExj8IwDIX/ipUZkICR6dCJlYWt7ZC2hlgKNorTO/V+/ZmcikBwO6Mdv+89O1Xllm7m9oyflLDLJGzlHA4BIcm3gmK0NvZADNmatTtI7QC5Bzn+dThh9FelBrqAH7Kcrex8jCMcKWZMoJ1nnQTZtxFvPK7dLsn5kXlPXNT8bnlcM6vcyg61lRweD7crBsZmQDJp+g+zMatX2bRMSpGWZIvitjb6xzR++yLkEzGCZx/HH9QnE7Wn3oy6IKJ4TYVTlhaD/yIxv3aEQYlPEHBIpMbXsmPzCw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}, {"Name", type text}, {"Description", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "CrossFilteringBehavior Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

