table 'Data Source Isolation ENUM'
	lineageTag: e592c738-ac2a-415a-925f-7267865c714d

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: e380b58c-3df7-42e9-968d-4836854401ef
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column Isolation
		dataType: string
		lineageTag: 7010debe-a0a7-437d-8c8b-a77335fdec47
		summarizeBy: none
		sourceColumn: Isolation

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 3e5fe241-86af-4bd7-a25f-f46eecf295d1
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition 'Data Source Isolation ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZZBBbsQwCEWv8uV1VKm9Qm/QdpeZBYmJYinBI0NGze2Lk5nKVZcg/uNB34fX0IUPpvie1zUZRy+/5qS407Ix9MZjmhIrbCaDGhmvLKa4yEgi2VA8jEhG58hMioFZsOZYk7HDsBnq5HissNq6yLAj28wFVkiURktZ9CVcuz68ucOn0E3nbH91WHQrTxlPn3sPA+eR7A7+dUQSUIuHc5qSlmV3J9Gk5uMd3DxNTqjg5tJ/mMIjpzt7Vx+WyNOh40953niqVaSBv+uKiIe0s0sTadB+//UH", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}, {"Name", type text}, {"Description", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "Isolation"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

