table 'Measures TM'
	lineageTag: db63c55f-4661-4a56-8130-925d189e7f5c

	column ID
		dataType: double
		lineageTag: 1e52cdff-6b54-4922-8560-8b9b28581ed7
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TableID
		dataType: double
		lineageTag: 5419cf6b-eefe-4082-8eb5-10475d2f4062
		summarizeBy: none
		sourceColumn: TableID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Measure Name'
		dataType: string
		lineageTag: e2c31765-bbdf-4df8-ba62-1ceed4c414f0
		summarizeBy: none
		sourceColumn: Measure Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 89b702c0-7f56-4cce-9fa7-b40e639d5837
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: int64
		formatString: 0
		lineageTag: 44f780a2-359a-4704-b472-24373972a210
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Expression
		dataType: string
		lineageTag: 341b2bc2-7836-423c-8fb8-bf714f5da6b0
		summarizeBy: none
		sourceColumn: Expression

		annotation SummarizationSetBy = Automatic

	column FormatString
		dataType: string
		lineageTag: 5941a62e-aeb1-4312-bc36-8b1b4c0fde98
		summarizeBy: none
		sourceColumn: FormatString

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 47df360a-5742-42cf-98e6-a788127e3ac4
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: int64
		formatString: 0
		lineageTag: 9d6b911f-4723-47d4-8d06-6aaff7a91252
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 62e6b367-e51d-4fd3-9cd7-8d125de7d3ad
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column StructureModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: a1ae5db8-eab3-4fa2-a79e-dca0c61aa73d
		summarizeBy: none
		sourceColumn: StructureModifiedTime

		annotation SummarizationSetBy = Automatic

	column KPIID
		dataType: double
		lineageTag: 27a11704-f6b0-4316-95bb-a337d5896a18
		summarizeBy: count
		sourceColumn: KPIID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsSimpleMeasure
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0d9c0141-4f8f-44dc-8d2e-587b0d9a8f13
		summarizeBy: none
		sourceColumn: IsSimpleMeasure

		annotation SummarizationSetBy = Automatic

	column ErrorMessage
		dataType: string
		lineageTag: 3dcd686d-88c1-44b8-92e5-a4c6f4cf496f
		summarizeBy: none
		sourceColumn: ErrorMessage

		annotation SummarizationSetBy = Automatic

	column DisplayFolder
		dataType: string
		lineageTag: e4a6ea4d-c5e5-43d8-86ba-158f4324b85e
		summarizeBy: none
		sourceColumn: DisplayFolder

		annotation SummarizationSetBy = Automatic

	column DetailRowsDefinitionID
		dataType: double
		lineageTag: 82435233-9b0e-484f-8e5e-90e2503709f1
		summarizeBy: count
		sourceColumn: DetailRowsDefinitionID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Hidden Icon' = IF('Measures TM'[IsHidden]=TRUE(),"❌", "👓")
		lineageTag: fe3f1705-5eed-49b4-af76-b848ed6f8bc5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TableObjectKey = RELATED('Tables TM'[Table Name]) & "-" & 'Measures TM'[Measure Name]
		lineageTag: 0f9cc3b9-362f-4d8a-9256-8458996d8c45
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DataCategory
		dataType: string
		lineageTag: 6615f7ab-0fde-4341-b6c0-f4ad958f5e80
		summarizeBy: none
		sourceColumn: DataCategory

		annotation SummarizationSetBy = Automatic

	column LineageTag
		dataType: string
		lineageTag: 83074795-9edb-427b-9690-762a766ccc7f
		summarizeBy: none
		sourceColumn: LineageTag

		annotation SummarizationSetBy = Automatic

	column SourceLineageTag
		dataType: string
		lineageTag: 6d9f877b-7837-47c4-9da5-7f1930bb2b62
		summarizeBy: none
		sourceColumn: SourceLineageTag

		annotation SummarizationSetBy = Automatic

	partition 'Measures TM' = m
		mode: import
		queryGroup: 'Meta Data'
		source =
				let
				    #"Measures TM" = AnalysisServices.Database(serverURL, modelName, [Query="SELECT * FROM $System.TMSCHEMA_MEASURES", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(#"Measures TM",{{"Name", "Measure Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

