table 'Partition Type ENUM'
	isHidden
	lineageTag: 07c8a5b0-59c3-486c-b61a-18065f294ec3

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: 9ba49842-be35-40fd-aa64-eaa36a01a1fd
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column 'Partition Type'
		dataType: string
		lineageTag: 64a3ca20-b5cb-4a60-9254-19e4961cc09c
		summarizeBy: none
		sourceColumn: Partition Type

		annotation SummarizationSetBy = Automatic

	partition 'Partition Type ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQosTS2qVIrViVYyAvKcE3OSS3MSS1JTwELGQCG//LxUMMcEyPEFs0yBLNe8kswSiEZzJI2Z+XnuRfmlBUqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "Partition Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

