table 'Relationships TM'
	lineageTag: 0a77027a-b54b-4d6c-9909-12410ea3382c

	column ID
		dataType: double
		lineageTag: 9803e32d-d83a-4d4e-a8f2-01408792092d
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModelID
		dataType: double
		lineageTag: 3a5dc030-19dd-449f-97e4-27964df91513
		summarizeBy: count
		sourceColumn: ModelID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Name
		dataType: string
		lineageTag: 8d163d29-5c6e-4e8c-8d8a-6e73eb5f661d
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column IsActive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b639b49-60d8-4536-a3b4-3ac1603bb927
		summarizeBy: none
		sourceColumn: IsActive

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: int64
		formatString: 0
		lineageTag: 57db7ccd-06b4-469f-be11-6b6b955265da
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column CrossFilteringBehavior
		dataType: int64
		formatString: 0
		lineageTag: 67b896d8-6229-4932-9c4b-11d899c26f01
		summarizeBy: none
		sourceColumn: CrossFilteringBehavior

		annotation SummarizationSetBy = Automatic

	column JoinOnDateBehavior
		dataType: int64
		formatString: 0
		lineageTag: 00d2d1fe-6de5-46f7-a1b3-1235ac9a45a8
		summarizeBy: none
		sourceColumn: JoinOnDateBehavior

		annotation SummarizationSetBy = Automatic

	column RelyOnReferentialIntegrity
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 029b94a0-a75f-4016-a412-4e5cae89105c
		summarizeBy: none
		sourceColumn: RelyOnReferentialIntegrity

		annotation SummarizationSetBy = Automatic

	column FromTableID
		dataType: double
		lineageTag: 9de1b3b3-baf0-4a42-8d69-6d9ff69401d0
		summarizeBy: none
		sourceColumn: FromTableID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FromColumnID
		dataType: double
		lineageTag: e37e745e-66d7-4ef4-b4e4-ba5191ad01bb
		summarizeBy: none
		sourceColumn: FromColumnID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FromCardinality
		dataType: int64
		formatString: 0
		lineageTag: 62fa3fd4-a792-4bd1-8b1b-b44862aa5183
		summarizeBy: sum
		sourceColumn: FromCardinality

		annotation SummarizationSetBy = Automatic

	column ToTableID
		dataType: double
		lineageTag: 39672271-ff88-4ce9-92ef-1d5abf204d46
		summarizeBy: none
		sourceColumn: ToTableID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ToColumnID
		dataType: double
		lineageTag: 8daab489-6b9b-4b72-b7fd-6c9a7afeae03
		summarizeBy: none
		sourceColumn: ToColumnID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ToCardinality
		dataType: int64
		formatString: 0
		lineageTag: 49bbdbe4-0cc2-44c0-8d3f-77964a2c6d89
		summarizeBy: sum
		sourceColumn: ToCardinality

		annotation SummarizationSetBy = Automatic

	column State
		dataType: int64
		formatString: 0
		lineageTag: e8c8e552-02b8-4585-85de-78386e0cfc88
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column RelationshipStorageID
		dataType: double
		lineageTag: 9d116c63-10ee-434e-af74-55d5e403b6f8
		summarizeBy: count
		sourceColumn: RelationshipStorageID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RelationshipStorage2ID
		dataType: double
		lineageTag: b46d4e0c-1d6d-480b-b5bb-b95b53ecdb20
		summarizeBy: count
		sourceColumn: RelationshipStorage2ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModifiedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 84a82d06-02d7-45a4-b2d8-d48bd8710d02
		summarizeBy: none
		sourceColumn: ModifiedTime

		annotation SummarizationSetBy = Automatic

	column RefreshedTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 95a7f97c-b965-49a1-8179-b380a0c119fc
		summarizeBy: none
		sourceColumn: RefreshedTime

		annotation SummarizationSetBy = Automatic

	column SecurityFilteringBehavior
		dataType: int64
		formatString: 0
		lineageTag: 1a78944b-f8d6-4fda-97f9-2ab958929690
		summarizeBy: none
		sourceColumn: SecurityFilteringBehavior

		annotation SummarizationSetBy = Automatic

	column FromCardinalityName
		dataType: string
		lineageTag: 4eee8d3f-4c6a-4f8e-b3b7-9cf3ba24207f
		summarizeBy: none
		sourceColumn: FromCardinalityName

		annotation SummarizationSetBy = Automatic

	column ToCardinalityName
		dataType: string
		lineageTag: c86519d6-136f-4c94-92c8-0b0b3f770e09
		summarizeBy: none
		sourceColumn: ToCardinalityName

		annotation SummarizationSetBy = Automatic

	column Cardinality = 'Relationships TM'[FromCardinalityName] & " to " &  'Relationships TM'[ToCardinalityName]
		lineageTag: d470af82-61db-4d02-9058-11192c0bc130
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Cardinality Icon' = ```
			
			SWITCH('Relationships TM'[FromCardinalityName], "Many", "✳️", "One", "1️⃣", "NA")
			&
			" 🔗 "
			&
			SWITCH('Relationships TM'[ToCardinalityName], "Many", "✳️", "One", "1️⃣", "NA")
			
			```
		lineageTag: ed46bc1c-0c03-42f1-a24f-72d36daf2b84
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Cross Filtering Behavior Icon' = IF(RELATED('CrossFilteringBehavior ENUM'[CrossFilteringBehavior Name])="OneDirection", "⤴️", "🔃")
		lineageTag: e97ef5bf-2d94-4e8c-96b6-c230025c2594
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Relationships TM' = m
		mode: import
		queryGroup: 'Meta Data'
		source =
				let
				    #"Relationships TM" = AnalysisServices.Database(serverURL, modelName, [Query="SELECT * FROM $System.TMSCHEMA_RELATIONSHIPS", Implementation="2.0"]),
				    #"Merged Queries" = Table.NestedJoin(#"Relationships TM", {"FromCardinality"}, #"Cardinality ENUM", {"Enum"}, "Cardinality ENUM", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"ToCardinality"}, #"Cardinality ENUM", {"Enum"}, "Cardinality ENUM.1", JoinKind.LeftOuter),
				    #"Expanded Cardinality ENUM" = Table.ExpandTableColumn(#"Merged Queries1", "Cardinality ENUM", {"Name"}, {"Name.1"}),
				    #"Expanded Cardinality ENUM.1" = Table.ExpandTableColumn(#"Expanded Cardinality ENUM", "Cardinality ENUM.1", {"Name"}, {"Name.2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Cardinality ENUM.1",{{"Name.1", "FromCardinalityName"}, {"Name.2", "ToCardinalityName"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

