table 'Relationship Type ENUM'
	lineageTag: 91ed53cc-0d18-49d1-82bf-9b4d3b90cb91

	column Enum
		dataType: int64
		formatString: 0
		lineageTag: a7a8596d-eb0b-4c6e-97ee-e5ee2ca844d8
		summarizeBy: none
		sourceColumn: Enum

		annotation SummarizationSetBy = Automatic

	column 'Relationship Type Name'
		dataType: string
		lineageTag: 66242e0f-b962-40a2-9427-0fda85f85c47
		summarizeBy: none
		sourceColumn: Relationship Type Name

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 2c87aa3f-5a16-4319-8fef-be824f68a59c
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition 'Relationship Type ENUM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrOzEvPSXXOzynNzQNyFfzyi3ITcxSSwQK6EEqhKDUnsSQzP684I7NAKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Enum = _t, Name = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Enum", Int64.Type}, {"Name", type text}, {"Description", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Name", "Relationship Type Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

