table 'Tables TM'
	lineageTag: 06b785cb-dabf-48c1-a1b2-988d841629f7

	column ID
		dataType: double
		lineageTag: dc02f151-c0f9-4845-a98c-0eda6d053ecd
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModelID
		dataType: double
		lineageTag: ef9b0fc4-1fc0-45b7-a789-a8ae3d2f46ec
		summarizeBy: none
		sourceColumn: ModelID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Table Name'
		dataType: string
		lineageTag: 952bcdda-f124-4bb3-a177-86e16cd2946f
		summarizeBy: none
		sourceColumn: Table Name

		annotation SummarizationSetBy = Automatic

	column DataCategory
		dataType: string
		lineageTag: 2eb2633f-0806-4ab0-8b70-c6ddb6141aed
		summarizeBy: none
		sourceColumn: DataCategory

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 7318129d-87fe-4ba2-911c-2684bf7a7e16
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column IsHidden
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2b2bc2b-44a2-4cb1-aed6-b7e67ac2a641
		summarizeBy: none
		sourceColumn: IsHidden

		annotation SummarizationSetBy = Automatic

	column TableStorageID
		dataType: double
		lineageTag: 206e93eb-1f4c-4470-a1ac-ad38ef5ebf64
		summarizeBy: count
		sourceColumn: TableStorageID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modified
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: ea24c801-166e-47ef-8047-0679d47e66e1
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Structure Modified'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 7ea07635-fb4b-45d3-a999-6717d27f5a7c
		summarizeBy: none
		sourceColumn: Structure Modified

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SystemFlags
		dataType: int64
		formatString: 0
		lineageTag: 18f1bd01-b59c-458e-a4dc-bcaa32e55ea4
		summarizeBy: sum
		sourceColumn: SystemFlags

		annotation SummarizationSetBy = Automatic

	column ShowAsVariationsOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 683f99e0-d356-4375-90ba-091671d329ca
		summarizeBy: none
		sourceColumn: ShowAsVariationsOnly

		annotation SummarizationSetBy = Automatic

	column IsPrivate
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7ea87411-8265-487f-bbec-6676a906ea54
		summarizeBy: none
		sourceColumn: IsPrivate

		annotation SummarizationSetBy = Automatic

	column DefaultDetailRowsDefinitionID
		dataType: double
		lineageTag: 9066147d-7eef-40f8-bdad-bd35c0d59cc4
		summarizeBy: count
		sourceColumn: DefaultDetailRowsDefinitionID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Hidden Icon' = IF('Tables TM'[IsHidden]=TRUE(),"❌", "👓")
		lineageTag: 7f98a97d-f5ee-490f-a63a-771cc4b83274
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AlternateSourcePrecedence
		dataType: int64
		formatString: 0
		lineageTag: 44d4d6b5-6447-4cc1-a13d-374fe2ebf0b3
		summarizeBy: sum
		sourceColumn: AlternateSourcePrecedence

		annotation SummarizationSetBy = Automatic

	column RefreshPolicyID
		dataType: double
		lineageTag: e35b0cc7-b2a7-4366-8c3f-52d82f38956f
		summarizeBy: count
		sourceColumn: RefreshPolicyID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CalculationGroupID
		dataType: double
		lineageTag: 72b8be1c-f1d0-4781-85fc-ef252d7a7a95
		summarizeBy: count
		sourceColumn: CalculationGroupID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExcludeFromModelRefresh
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5b071703-cca4-41a8-9381-e53143c21120
		summarizeBy: none
		sourceColumn: ExcludeFromModelRefresh

		annotation SummarizationSetBy = Automatic

	column LineageTag
		dataType: string
		lineageTag: 89d58021-983a-44e7-a206-14f8d7b94699
		summarizeBy: none
		sourceColumn: LineageTag

		annotation SummarizationSetBy = Automatic

	column SourceLineageTag
		dataType: string
		lineageTag: 3e03cfb5-d2a4-4d0e-8c44-77e2afa0fee3
		summarizeBy: none
		sourceColumn: SourceLineageTag

		annotation SummarizationSetBy = Automatic

	column SystemManaged
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b127cd9-9d18-429b-a99a-715a4dd00d9c
		summarizeBy: none
		sourceColumn: SystemManaged

		annotation SummarizationSetBy = Automatic

	partition 'Tables TM' = m
		mode: import
		queryGroup: 'Meta Data'
		source =
				let
				    Source = AnalysisServices.Database(serverURL, modelName, [Query="SELECT * FROM $System.TMSCHEMA_TABLES", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Name", "Table Name"}, {"StructureModifiedTime", "Structure Modified"}, {"ModifiedTime", "Modified"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

