table Units
	lineageTag: 90596c6a-41c3-43f9-a21a-48e5e87bddd9

	column UnitKey
		dataType: int64
		formatString: 0
		lineageTag: d48b3850-2fd9-43f8-a088-e870e3e29f06
		summarizeBy: count
		sourceColumn: UnitKey

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: c27bd987-3f4e-4e6a-82a9-dd13f9c58f6c
		summarizeBy: none
		sourceColumn: Unit
		sortByColumn: UnitKey

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column UnitValue
		dataType: int64
		formatString: 0
		lineageTag: b7c07743-0969-427c-8148-f1bc621a594a
		summarizeBy: sum
		sourceColumn: UnitValue

		annotation SummarizationSetBy = Automatic

	partition Units = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUUqqLEktBtKGSrE60UpGQFZ2Zk4+XNTAyAQsYQzk5KamJyIkTCxMzc3AciZAfnomspy5sbmJoQVIaywA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [UnitKey = _t, Unit = _t, UnitValue = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"UnitKey", Int64.Type}, {"Unit", type text}, {"UnitValue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

